sudo: required
dist: precise
language: cpp

git:
  submodules: false
  
before_install:
    - if [ -f .gitmodules ] ; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules ; fi
    - git submodule update --init 
    - git submodule foreach "if [ -f .gitmodules ] ; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules ; fi &&  git submodule update --init && git submodule foreach \"if [ -f .gitmodules ] ; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules ; fi &&  git submodule update --init \""
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - cmake
            - cmake-data
            - g++-5
            - libboost-all-dev
      env: COMPILER=g++-5
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise
#            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.9
#      env: COMPILER=clang++-3.9

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - make test
